### ISSUE TITLE
reqwest::Error Error("missing field `meta`", line: 1, column: 211)

### ISSUE THREAD

**Issue by 0xdevalias** [etopiei/up-cli#3]
Just ran into the following after setting up the CLI  exporting my token:

```
⇒  up-cli
Error: reqwest::Error { kind: Decode, source: Error("missing field `meta`", line: 1, column: 211) }
```

I expect that the API response has changed since this CLI was written or similar so that it's no longer matching the struct, but I haven't looked into the code to confirm that.

---

**Edit:** This seems to be the first call being made, to the `/util/ping` endpoint:

- https://github.com/etopiei/up-cli/blob/master/src/main.rs#L11-L19
- https://developer.up.com.au/#get_util_ping

Which is expecting a `PingResponse`, which appears to be defined in:

- https://github.com/etopiei/up-cli/blob/master/src/up.rs#L5-L16

When testing externally with postman, the endpoint seems as though it should be returning data that matches this struct:

```json
{"meta":{"id":"abc123-abc-123-abc-abc123","statusEmoji":"⚡️"}}
```

**Comment by etopiei** [comment]
Thanks for this report @0xdevalias! And sorry I took so long to get to this, I only saw the issue just now. There is a new version (0.1.1) coming out shortly that should fix this bug.

**Comment by etopiei** [comment]
Closing now that 0.1.1 has been released: https://crates.io/crates/up-cli/0.1.1

Feel free to re-open if there are any more persistent issues. :slightly_smiling_face:
